### PR TITLE
Set PR limit to 10/hour

### PR DESCRIPTION
**Pull request by rarkins**
Sets Renovate's hourly rate limit for new PRs to 10.

### CODE REVIEW

**Comment by rarkins** [comment]
Alternatively you could set it to 0 to disable any hourly limit

**Comment by rarkins** [comment]
Cc @abernix

**Review by abernix — APPROVED** [review]
I think this makes a lot of sense for this configuration, especially since it's a docs-specific configuration (and the CI runs quickly) and since we have so many "primary" branches on these repositories.  Thanks!

**Comment by abernix** [comment]
cc @hwillson.

**Pull request merged**
